name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: [docs/**, .github/**]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2
      - name: Install dependencies
        run: pnpm install --recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Build website
        working-directory: ./
        run: |
          cd visual-editor
          pnpm run build
          cd ../docs 
          pnpm run build;
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build

